### PR TITLE
Cohesion ratio parameter

### PR DESCRIPTION
**Pull request by iMaks99**
Added new parameter `cohesionScore` to plugin and comparison with project's `score`. If `score` less than `cohesionScore` exception is thown

### CODE REVIEW

**Comment by iMaks99** [comment]
@paulodamaso as you suggested all maven code we moved here

**Comment by yegor256** [comment]
@iMaks99 try to build it with `mvn clean install -Pqulice`. I suspect there will be problems

**Comment by iMaks99** [comment]
@yegor256 I built project with `mvn clean install -Pqulice` and fixed all check failures

**Comment by paulodamaso** [comment]
@iMaks99 The build is still failing in Travis, please take a look

**Comment by iMaks99** [comment]
@paulodamaso there were codestyle issuies

**Comment by paulodamaso** [comment]
@iMaks99 Thank you!

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek-maven-plugin#14` is not assigned, can't get performer

**Pull request merged**
